CREATE TABLE IF NOT EXISTS Alarm (ID_Alarm serial, PRIMARY KEY (ID_Alarm));

ALTER TABLE IF EXISTS Alarm ADD COLUMN IF NOT EXISTS ID_Camera integer NOT NULL;

ALTER TABLE IF EXISTS Alarm ADD COLUMN IF NOT EXISTS SBegin bigint NOT NULL;

ALTER TABLE IF EXISTS Alarm ADD COLUMN IF NOT EXISTS SEnd bigint NOT NULL;

ALTER TABLE IF EXISTS Alarm ADD COLUMN IF NOT EXISTS StartMessage character varying(512) NULL;


CREATE TABLE IF NOT EXISTS Archive (ID_Archive serial, PRIMARY KEY (ID_Archive));

ALTER TABLE IF EXISTS Archive ADD COLUMN IF NOT EXISTS Path character varying(512) NOT NULL;

ALTER TABLE IF EXISTS Archive ADD COLUMN IF NOT EXISTS Active boolean NOT NULL DEFAULT True;


CREATE TABLE IF NOT EXISTS Camera (ID_Camera serial, PRIMARY KEY (ID_Camera));

ALTER TABLE IF EXISTS Camera ADD COLUMN IF NOT EXISTS ConnectionString character varying(512) NOT NULL;

ALTER TABLE IF EXISTS Camera ADD COLUMN IF NOT EXISTS Secondary character varying(512) NULL;

ALTER TABLE IF EXISTS Camera ADD COLUMN IF NOT EXISTS Name character varying(128) NULL;

ALTER TABLE IF EXISTS Camera ADD COLUMN IF NOT EXISTS Active boolean NOT NULL DEFAULT True;

ALTER TABLE IF EXISTS Camera ADD COLUMN IF NOT EXISTS Schedule_Type integer NOT NULL DEFAULT 0;

ALTER TABLE IF EXISTS Camera ADD COLUMN IF NOT EXISTS Deleted boolean NOT NULL DEFAULT False;


CREATE TABLE IF NOT EXISTS Config (ID_Config serial, PRIMARY KEY (ID_Config));

ALTER TABLE IF EXISTS Config ADD COLUMN IF NOT EXISTS Category character varying(50) NULL;

ALTER TABLE IF EXISTS Config ADD COLUMN IF NOT EXISTS Name character varying(50) NULL;

ALTER TABLE IF EXISTS Config ADD COLUMN IF NOT EXISTS Data character varying(8000) NULL;


CREATE TABLE IF NOT EXISTS Fill (ID_Fill serial, PRIMARY KEY (ID_Fill));

ALTER TABLE IF EXISTS Fill ADD COLUMN IF NOT EXISTS ID_Camera integer NOT NULL;

ALTER TABLE IF EXISTS Fill ADD COLUMN IF NOT EXISTS ID_Archive integer NOT NULL;

ALTER TABLE IF EXISTS Fill ADD COLUMN IF NOT EXISTS SBegin bigint NOT NULL;

ALTER TABLE IF EXISTS Fill ADD COLUMN IF NOT EXISTS SEnd bigint NOT NULL;


CREATE TABLE IF NOT EXISTS Log (ID_Log serial, PRIMARY KEY (ID_Log));

ALTER TABLE IF EXISTS Log ADD COLUMN IF NOT EXISTS Type integer NOT NULL;

ALTER TABLE IF EXISTS Log ADD COLUMN IF NOT EXISTS Source_Type integer NOT NULL;

ALTER TABLE IF EXISTS Log ADD COLUMN IF NOT EXISTS ID_Source integer NOT NULL;

ALTER TABLE IF EXISTS Log ADD COLUMN IF NOT EXISTS STime bigint NOT NULL;

ALTER TABLE IF EXISTS Log ADD COLUMN IF NOT EXISTS Message character varying(512) NOT NULL;


CREATE TABLE IF NOT EXISTS Motion (ID_Motion serial, PRIMARY KEY (ID_Motion));

ALTER TABLE IF EXISTS Motion ADD COLUMN IF NOT EXISTS ID_Camera integer NOT NULL;

ALTER TABLE IF EXISTS Motion ADD COLUMN IF NOT EXISTS SBegin bigint NOT NULL;

ALTER TABLE IF EXISTS Motion ADD COLUMN IF NOT EXISTS SEnd bigint NOT NULL;


CREATE TABLE IF NOT EXISTS Plugin (ID_Plugin serial, PRIMARY KEY (ID_Plugin));

ALTER TABLE IF EXISTS Plugin ADD COLUMN IF NOT EXISTS Name character varying(128) NOT NULL;

ALTER TABLE IF EXISTS Plugin ADD COLUMN IF NOT EXISTS FileName character varying(128) NOT NULL;

ALTER TABLE IF EXISTS Plugin ADD COLUMN IF NOT EXISTS PictureType integer NOT NULL DEFAULT 0;


CREATE TABLE IF NOT EXISTS Plugin_Camera (ID_Plugin_Camera serial, PRIMARY KEY (ID_Plugin_Camera));

ALTER TABLE IF EXISTS Plugin_Camera ADD COLUMN IF NOT EXISTS ID_Plugin integer NOT NULL;

ALTER TABLE IF EXISTS Plugin_Camera ADD COLUMN IF NOT EXISTS ID_Camera integer NOT NULL;

ALTER TABLE IF EXISTS Plugin_Camera ADD COLUMN IF NOT EXISTS APrimary boolean NOT NULL DEFAULT False;


CREATE TABLE IF NOT EXISTS Plugin_Param (ID_Plugin_Param serial, PRIMARY KEY (ID_Plugin_Param));

ALTER TABLE IF EXISTS Plugin_Param ADD COLUMN IF NOT EXISTS ID_Plugin_Camera integer NOT NULL;

ALTER TABLE IF EXISTS Plugin_Param ADD COLUMN IF NOT EXISTS Param character varying(64) NOT NULL;

ALTER TABLE IF EXISTS Plugin_Param ADD COLUMN IF NOT EXISTS Value character varying(64) NOT NULL;


CREATE TABLE IF NOT EXISTS Schedule (ID_Schedule serial, PRIMARY KEY (ID_Schedule));

ALTER TABLE IF EXISTS Schedule ADD COLUMN IF NOT EXISTS ID_Camera integer NOT NULL;

ALTER TABLE IF EXISTS Schedule ADD COLUMN IF NOT EXISTS Day integer NOT NULL;

ALTER TABLE IF EXISTS Schedule ADD COLUMN IF NOT EXISTS SBegin integer NOT NULL;

ALTER TABLE IF EXISTS Schedule ADD COLUMN IF NOT EXISTS SEnd integer NOT NULL;


CREATE TABLE IF NOT EXISTS SecondaryVideo (ID_SecondaryVideo serial, PRIMARY KEY (ID_SecondaryVideo));

ALTER TABLE IF EXISTS SecondaryVideo ADD COLUMN IF NOT EXISTS ID_Archive integer NOT NULL;

ALTER TABLE IF EXISTS SecondaryVideo ADD COLUMN IF NOT EXISTS ID_Camera integer NOT NULL;

ALTER TABLE IF EXISTS SecondaryVideo ADD COLUMN IF NOT EXISTS SBegin bigint NOT NULL;

ALTER TABLE IF EXISTS SecondaryVideo ADD COLUMN IF NOT EXISTS SEnd bigint NOT NULL;


CREATE TABLE IF NOT EXISTS Video (ID_Video serial, PRIMARY KEY (ID_Video));

ALTER TABLE IF EXISTS Video ADD COLUMN IF NOT EXISTS ID_Archive integer NOT NULL;

ALTER TABLE IF EXISTS Video ADD COLUMN IF NOT EXISTS ID_Camera integer NOT NULL;

ALTER TABLE IF EXISTS Video ADD COLUMN IF NOT EXISTS SBegin bigint NOT NULL;

ALTER TABLE IF EXISTS Video ADD COLUMN IF NOT EXISTS SEnd bigint NOT NULL;

