CREATE TABLE IF NOT EXISTS Event (ID_Event serial, PRIMARY KEY (ID_Event));

ALTER TABLE IF EXISTS Event ADD COLUMN IF NOT EXISTS ID_Camera integer NOT NULL;

ALTER TABLE IF EXISTS Event ADD COLUMN IF NOT EXISTS Event_Date bigint NOT NULL;


CREATE TABLE IF NOT EXISTS Path (ID_Path serial, PRIMARY KEY (ID_Path));

ALTER TABLE IF EXISTS Path ADD COLUMN IF NOT EXISTS Name character varying(256) NULL;   

ALTER TABLE IF EXISTS Path ADD COLUMN IF NOT EXISTS Distance int NOT NULL;


CREATE TABLE IF NOT EXISTS Zone (ID_Zone serial, PRIMARY KEY (ID_Zone));

ALTER TABLE IF EXISTS Zone ADD COLUMN IF NOT EXISTS ID_Event integer NOT NULL;

ALTER TABLE IF EXISTS Zone ADD COLUMN IF NOT EXISTS Square_From smallint NOT NULL;

ALTER TABLE IF EXISTS Zone ADD COLUMN IF NOT EXISTS Square_To smallint NOT NULL;

ALTER TABLE IF EXISTS Zone ADD COLUMN IF NOT EXISTS ID_Path int NOT NULL;

